-- begin DASHBOARD_WIDGET_TEMPLATE
alter table DASHBOARD_WIDGET_TEMPLATE add constraint FK_DASHBOARD_WIDGETEMPL_GROUP foreign key (GROUP_ID) references DASHBOARD_WIDGET_TEMPLATE_GROUP(ID)^
create index IDX_DASHBOARD_WIDGTEMP_GROUP on DASHBOARD_WIDGET_TEMPLATE (GROUP_ID)^
-- end DASHBOARD_WIDGET_TEMPLATE
-- begin DASHBOARD_WIDGET_TEMPLATE_GROUP
create unique index IDX_DASHBOARD_WITEGR_UK_NAME on DASHBOARD_WIDGET_TEMPLATE_GROUP (NAME, DELETE_TS) ^
-- end DASHBOARD_WIDGET_TEMPLATE_GROUP
-- begin DASHBOARD_DASHBOARD_GROUP
create unique index IDX_DASHBOARD_GROUP_UK_NAME on DASHBOARD_DASHBOARD_GROUP (NAME, DELETE_TS) ^
-- end DASHBOARD_DASHBOARD_GROUP
-- begin DASHBOARD_PERSISTENT_DASHBOARD
alter table DASHBOARD_PERSISTENT_DASHBOARD add constraint FK_DASHBOARD_PERSIDASHB_GROUP foreign key (GROUP_ID) references DASHBOARD_DASHBOARD_GROUP(ID)^
create unique index IDX_DASHBOARD_PEDA_UK_RENA on DASHBOARD_PERSISTENT_DASHBOARD (REFERENCE_NAME, DELETE_TS) ^
create index IDX_DASHBOARD_PERSDASH_GROUP on DASHBOARD_PERSISTENT_DASHBOARD (GROUP_ID)^
-- end DASHBOARD_PERSISTENT_DASHBOARD
