-- begin AMXD_PERSISTENT_DASHBOARD
alter table AMXD_PERSISTENT_DASHBOARD add constraint FK_AMXD_PERSISTENT_DASHBOARD_ON_DASHBOARD_GROUP foreign key (DASHBOARD_GROUP_ID) references AMXD_DASHBOARD_GROUP(ID)^
create unique index IDX_AMXD_PERSISTENT_DASHBOARD_UNIQ_REFERENCE_NAME on AMXD_PERSISTENT_DASHBOARD (REFERENCE_NAME) ^
create index IDX_AMXD_PERSISTENT_DASHBOARD_ON_DASHBOARD_GROUP on AMXD_PERSISTENT_DASHBOARD (DASHBOARD_GROUP_ID)^
-- end AMXD_PERSISTENT_DASHBOARD
-- begin AMXD_WIDGET_TEMPLATE
alter table AMXD_WIDGET_TEMPLATE add constraint FK_AMXD_WIDGET_TEMPLATE_ON_WIDGET_TEMPLATE_GROUP foreign key (WIDGET_TEMPLATE_GROUP_ID) references AMXD_WIDGET_TEMPLATE_GROUP(ID)^
create index IDX_AMXD_WIDGET_TEMPLATE_ON_WIDGET_TEMPLATE_GROUP on AMXD_WIDGET_TEMPLATE (WIDGET_TEMPLATE_GROUP_ID)^
-- end AMXD_WIDGET_TEMPLATE
-- begin AMXD_DASHBOARD_GROUP
create unique index IDX_AMXD_DASHBOARD_GROUP_UNIQ_NAME on AMXD_DASHBOARD_GROUP (NAME) ^
-- end AMXD_DASHBOARD_GROUP
-- begin AMXD_WIDGET_TEMPLATE_GROUP
create unique index IDX_AMXD_WIDGET_TEMPLATE_GROUP_UNIQ_NAME on AMXD_WIDGET_TEMPLATE_GROUP (NAME) ^
-- end AMXD_WIDGET_TEMPLATE_GROUP
