alter table AMXD_WIDGET_PARAMETER add column INTEGER_VALUE integer ;
alter table AMXD_WIDGET_PARAMETER add column STRING_VALUE varchar(255) ;
alter table AMXD_WIDGET_PARAMETER add column DECIMAL_VALUE decimal(19, 2) ;
alter table AMXD_WIDGET_PARAMETER add column DATE_VALUE date ;
alter table AMXD_WIDGET_PARAMETER add column BOOL_VALUE boolean ;
alter table AMXD_WIDGET_PARAMETER add column LONG_VALUE bigint ;
alter table AMXD_WIDGET_PARAMETER add column DOUBLE_VALUE double precision ;
alter table AMXD_WIDGET_PARAMETER add column ENTITY_VALUE_ENTITY_ID uuid ;
alter table AMXD_WIDGET_PARAMETER add column ENTITY_VALUE_META_CLASS_NAME varchar(255) ;
alter table AMXD_WIDGET_PARAMETER add column ENTITY_VALUE_VIEW_NAME varchar(255) ;
