alter table DASHBOARD_DASHBOARD_WIDGET add constraint FK_DASHBOARD_DASHBOARD_WIDGET_REPORT foreign key (REPORT_ID) references REPORT_REPORT(ID);
create index IDX_DASHBOARD_DASHBOARD_WIDGET_REPORT on DASHBOARD_DASHBOARD_WIDGET (REPORT_ID);
