alter table AMXD_DASHBOARD_WIDGET add constraint FK_AMXD_DASHBOARD_WIDGET_REPORT foreign key (REPORT_ID) references REPORT_REPORT(ID);
create index IDX_AMXD_DASHBOARD_WIDGET_REPORT on AMXD_DASHBOARD_WIDGET (REPORT_ID);
