-- begin AMXD_DASHBOARD_GROUP
create unique index IDX_AMXD_DASHBOARD_GROUP_UK_NAME on AMXD_DASHBOARD_GROUP (NAME) where DELETE_TS is null ^
-- end AMXD_DASHBOARD_GROUP
-- begin AMXD_PERSISTENT_DASHBOARD
alter table AMXD_PERSISTENT_DASHBOARD add constraint FK_AMXD_PERSISTENT_DASHBOARD_DASHBOARD_GROUP foreign key (DASHBOARD_GROUP_ID) references AMXD_DASHBOARD_GROUP(ID)^
create unique index IDX_AMXD_PERSISTENT_DASHBOARD_UK_REFERENCE_NAME on AMXD_PERSISTENT_DASHBOARD (REFERENCE_NAME) where DELETE_TS is null ^
create index IDX_AMXD_PERSISTENT_DASHBOARD_DASHBOARD_GROUP on AMXD_PERSISTENT_DASHBOARD (DASHBOARD_GROUP_ID)^
-- end AMXD_PERSISTENT_DASHBOARD
