-- begin AMXD_DASHBOARD
alter table AMXD_DASHBOARD add constraint FK_AMXD_DASHBOARD_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_AMXD_DASHBOARD_USER on AMXD_DASHBOARD (USER_ID)^
-- end AMXD_DASHBOARD
-- begin AMXD_DASHBOARD_WIDGET_LINK
alter table AMXD_DASHBOARD_WIDGET_LINK add constraint FK_AMXD_DASHBOARD_WIDGET_LINK_DASHBOARD foreign key (DASHBOARD_ID) references AMXD_DASHBOARD(ID)^
alter table AMXD_DASHBOARD_WIDGET_LINK add constraint FK_AMXD_DASHBOARD_WIDGET_LINK_DASHBOARD_WIDGET foreign key (DASHBOARD_WIDGET_ID) references AMXD_DASHBOARD_WIDGET(ID)^
create index IDX_AMXD_DASHBOARD_WIDGET_LINK_DASHBOARD on AMXD_DASHBOARD_WIDGET_LINK (DASHBOARD_ID)^
create index IDX_AMXD_DASHBOARD_WIDGET_LINK_DASHBOARD_WIDGET on AMXD_DASHBOARD_WIDGET_LINK (DASHBOARD_WIDGET_ID)^
-- end AMXD_DASHBOARD_WIDGET_LINK
-- begin AMXD_WIDGET_PARAMETER
alter table AMXD_WIDGET_PARAMETER add constraint FK_AMXD_WIDGET_PARAMETER_DASHBOARD_WIDGET foreign key (DASHBOARD_WIDGET_ID) references AMXD_DASHBOARD_WIDGET(ID)^
alter table AMXD_WIDGET_PARAMETER add constraint FK_AMXD_WIDGET_PARAMETER_DASHBOARD_WIDGET_LINK foreign key (DASHBOARD_WIDGET_LINK_ID) references AMXD_DASHBOARD_WIDGET_LINK(ID)^
alter table AMXD_WIDGET_PARAMETER add constraint FK_AMXD_WIDGET_PARAMETER_MASTER_PARAMETER foreign key (MASTER_PARAMETER_ID) references AMXD_WIDGET_PARAMETER(ID)^
create index IDX_AMXD_WIDGET_PARAMETER_DASHBOARD_WIDGET on AMXD_WIDGET_PARAMETER (DASHBOARD_WIDGET_ID)^
create index IDX_AMXD_WIDGET_PARAMETER_DASHBOARD_WIDGET_LINK on AMXD_WIDGET_PARAMETER (DASHBOARD_WIDGET_LINK_ID)^
create index IDX_AMXD_WIDGET_PARAMETER_MASTER_PARAMETER on AMXD_WIDGET_PARAMETER (MASTER_PARAMETER_ID)^
-- end AMXD_WIDGET_PARAMETER
-- begin AMXD_DASHBOARD_WIDGET
alter table AMXD_DASHBOARD_WIDGET add constraint FK_AMXD_DASHBOARD_WIDGET_REPORT foreign key (REPORT_ID) references REPORT_REPORT(ID)^
create index IDX_AMXD_DASHBOARD_WIDGET_REPORT on AMXD_DASHBOARD_WIDGET (REPORT_ID)^
-- end AMXD_DASHBOARD_WIDGET
